# store the tech that will fromat the code
repos:
  # remove unused imports
  - repo: https://github.com/hadialqattan/pycln.git
    rev: v2.1.3
    hooks:
      - id: pycln

  # import formatter with black configurations
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]

  # format code base
  - repo: https://github.com/psf/black
    rev: 23.1.0 # the version found in github release 
    hooks: 
      - id: black # this will search of .py files
        language_version: python3.9 # apply python 3.9 formatting rules